# ===== PROFIL ACTIF =====
spring.profiles.active=dev

# ===== ARCHIVAGE DES COMMANDES =====
commande.archivage.seuil=5

# ===== NOM DE L'APPLICATION =====
spring.application.name=pneu-shop-backend

# ===== PORT DU SERVEUR =====
server.port=8080

# ===== JPA COMMUNE =====
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# ===== STRIPE =====
stripe.secret.key=sk_test_VOTRE_CLE_SECRETE_ICI

# ===== JWT =====
jwt.secret=VotreCleSecreteTresLongueEtComplexePourJWT2026
jwt.expiration=86400000

# ===== UPLOAD IMAGES =====
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# ===== SWAGGER =====
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
